system:
  mode: 0 # 0 for graph mode, 1 for pynative mode in MindSpore
  distribute: True
  amp_level: O2
  amp_level_infer: O2 # running inference in O2 mode
  seed: 17
  log_interval: 100
  val_while_train: True
  drop_overflow_update: False
  ckpt_max_keep: 30

common:
  character_dict_path: &character_dict_path /home/mindocr/tongli/workspace/mindocr-fork_9/mindocr/utils/dict/table_master_structure_dict.txt
  max_text_len: &max_text_len 500
  batch_size: &batch_size 10
  box_format: &box_format 'xywh' # 'xywh', 'xyxy', 'xyxyxyxy'

model:
  type: table
  transform: null
  backbone:
    name: table_resnet_extra
    gcb_config:
      ratio: 0.0625
      headers: 1
      att_scale: False
      fusion_type: channel_add
      layers: [ False, True, True, True ]
    layers: [ 1,2,5,3 ]
  head:
    name: TableMasterHead
    out_channels: 43
    hidden_size: 512
    headers: 8
    dropout: 0.
    d_ff: 2024
    max_text_length: *max_text_len
    loc_reg_num: &loc_reg_num 4

postprocess:
  name: TableMasterLabelDecode
  character_dict_path: *character_dict_path
  box_shape: pad
  merge_no_span_structure: &merge_no_span_structure True

metric:
  name: TableMetric
  main_indicator: acc
  compute_bbox_metric: False
  box_format: *box_format

loss:
  name: TableMasterLoss
  ignore_index: 42 # set to len of dict + 3


scheduler:
  scheduler: constant
  lr: 0.001
  num_epochs: 16
  warmup_epochs: 0

#scheduler:
#  scheduler: multi_step_decay
#  milestones: [14, 17]
#  decay_rate: 0.1
#  lr: 0.001
#  num_epochs: 20
#  warmup_epochs: 1

#scheduler:
#  scheduler: multi_step_decay
#  milestones: [1, 4]
#  decay_rate: 0.1
#  lr: 0.001
#  num_epochs: 8
#  warmup_epochs: 0

#scheduler:
#  scheduler: multi_step_decay
#  milestones: [12, 15]
#  decay_rate: 0.1
#  lr: 0.001
#  num_epochs: 20
#  warmup_epochs: 0

#scheduler:
#  scheduler: 'cosine_decay'
#  lr: 0.001
#  min_lr: 0.00001
#  num_epochs: 20
#  warmup_epochs: 0
#  decay_epochs: 15


optimizer:
  opt: adam
  beta1: 0.9
  beta2: 0.999

loss_scaler:
  type: dynamic
  loss_scale: 512
  scale_factor: 2.0
  scale_window: 1000

train:
#  ckpt_save_dir: ./table_0918_try2_with_val_graph_O2_8p_follow_master_separated_layernorm_not_cls_n_box_layer_ep20_cosine_sche
#  ckpt_save_dir: ./table_0921_try2_with_val_graph_O2_8p_follow_master_separated_layernorm_not_cls_n_box_layer_ep20_cosine_sche2_decay_epoch15
#  ckpt_save_dir: ./table_0921_try3_finetune_from_table_0914_try1
#  ckpt_save_dir: ./table_0926_try1_reproduce_0914_try1_ep20
  ckpt_save_dir: ./table_1011_try2_continue_1011_try1_from_ep3_constant_lr_ep30_1warmup
  dataset_sink_mode: False
  ema: True
  dataset:
    type: PubTabDataset
    data_dir: /home/mindocr/tongli/data/pubtabnet/train/
    label_file_list: [/home/mindocr/tongli/data/pubtabnet/PubTabNet_2.0.0_train.jsonl]
#    data_dir: /home/mindocr/tongli/data/pubtabnet/val
#    label_file_list: [ /home/mindocr/tongli/data/pubtabnet/PubTabNet_2.0.0_val.jsonl ]
#    data_dir: /home/mindocr/tongli/data/pubtabnet/train_n_val
#    label_file_list: [ /home/mindocr/tongli/data/pubtabnet/PubTabNet_2.0.0_train_n_val.jsonl ]
    sample_ratio_list: [ 1.0 ]
    shuffle: True
    transform_pipeline:
      - DecodeImage:
          img_mode: BGR
          to_float32: false
      - TableMasterLabelEncode:
          character_dict_path: *character_dict_path
          learn_empty_box: False
          merge_no_span_structure: *merge_no_span_structure
          replace_empty_cell_token: True
          loc_reg_num: *loc_reg_num
          max_text_length: *max_text_len
      - ResizeTableImage:
          max_len: 480
          resize_bboxes: True
      - PaddingTableImage:
          size: [ 480, 480 ]
      - TableBoxEncode:
          in_box_format: *box_format
          out_box_format: *box_format
#      - NormalizeImage:
#          is_hwc: True
#          mean: [127.0, 127.0, 127.0]
#          std: [127.0, 127.0, 127.0]
      - NormalizeImageFromPaddle:
          scale: 1./255.
          mean: [0.5, 0.5, 0.5]
          std: [0.5, 0.5, 0.5]
          order: hwc
      - ToCHWImage:
    output_columns: [ "image", "structure", "bboxes", "bbox_masks", "shape" ]
    net_input_column_index: [ 0, 1 ]
    label_column_index: [ 1, 2, 3 ]

  loader:
    shuffle: True
    batch_size: *batch_size
    drop_remainder: True
    max_rowsize: 12
    num_workers: 1

eval:
  ckpt_load_path: ./table_1011_try2_continue_1011_try1_from_ep3_constant_lr_ep30_1warmup/best.ckpt
  dataset_sink_mode: False
  dataset:
    type: PubTabDataset
    data_dir: /home/mindocr/tongli/data/pubtabnet/val
    label_file_list: [ /home/mindocr/tongli/data/pubtabnet/PubTabNet_2.0.0_val.jsonl ]
    sample_ratio_list: [ 1.0 ]
    shuffle: False
    transform_pipeline:
      - DecodeImage:
          img_mode: BGR
          to_float32: True
      - TableMasterLabelEncode:
          character_dict_path: *character_dict_path
          learn_empty_box: False
          merge_no_span_structure: *merge_no_span_structure
          replace_empty_cell_token: True
          loc_reg_num: *loc_reg_num
          max_text_length: *max_text_len
      - ResizeTableImage:
          max_len: 480
          resize_bboxes: True
      - PaddingTableImage:
          size: [ 480, 480 ]
      - TableBoxEncode:
          in_box_format: *box_format
          out_box_format: *box_format
#      - NormalizeImage:
#          is_hwc: True
#          mean: [ 127.0, 127.0, 127.0 ]
#          std: [ 127.0, 127.0, 127.0 ]
      - NormalizeImageFromPaddle:
          scale: 1./255.
          mean: [ 0.5, 0.5, 0.5 ]
          std: [ 0.5, 0.5, 0.5 ]
          order: hwc
      - ToCHWImage:
    output_columns: [ "image", "structure", "bboxes", "bbox_masks", "shape" ]
    net_input_column_index: [ 0, 1 ]
    label_column_index: [ 0, 1, 2, 3, 4 ]

  loader:
    shuffle: False
    batch_size: 10
    drop_remainder: False
    max_rowsize: 12
    num_workers: 1
